# SERVER CONFIGURATION
server.port=8080
spring.application.name=userservice

# EUREKA CONFIGURATION
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# DEVTOOLS
spring.devtools.restart.enabled=true

# SPRING CLOUD CONFIG
# spring.config.import=optional:configserver:
spring.cloud.config.enabled=false

# H2 DATABASE CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.setting.web-allow-others=true

# DATASOURCE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:testdb2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=karthik
spring.datasource.password=karthik

# JPA / HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=
# createdrop or update ^^^^
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always