# SERVER CONFIGURATION
server.port=8020
spring.application.name=user-service

# EUREKA CONFIGURATION
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# DEVTOOLS
spring.devtools.restart.enabled=true

# SPRING CLOUD CONFIG
spring.config.import=optional:configserver:
spring.cloud.config.enabled=false

# H2 DATABASE CONSOLE
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# DATASOURCE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:testdb2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=karthik
spring.datasource.password=karthik

# JPA / HIBERNATE CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=createdrop
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# GATEWAY CONFIGURATION
spring.cloud.gateway.discovery.locator.enabled=false
gateway.ip=127.0.0.1

# JWT CONFIGURATION
#Duration: 864,000,000 ms = 864,000 seconds = 240 hours = 10 days.
token.expiration_time=864000000
token.secret=hfgry463hf746hf573ydh475fhy5739hfgry463hf746hf573ydh475fhy5739hfgry463hf746hf573ydh475fhy5739

# LOGIN URL
login.url.path=/users/login

spring.rabbitmq.listener.simple.auto-startup=false